### ISSUE TITLE
Live view doesn't work.


### ISSUE THREAD

**Issue by SanchoDev39** [Dev-Environments/VScode#67] opened 2024-10-14 11:02 UTC
ADD ISSUE DESCRIPTION HERE

Version: 1.85.1
Commit: 14633336
User Agent: Mozilla/5.0 (Android 14; Mobile; rv:125.0) Gecko/125.0 Firefox/125.0
Embedder: server-distro

**Comment by gbraad** [comment] 2024-10-16 17:42
duplicate of #66 ?

**Closed as completed** 2024-12-16 12:14 UTC
